### ISSUE TITLE
0.4.0 DEB Package missing QT6 depedancies

### ISSUE THREAD

**Issue by janteau** [CDrummond/melodeon#4]
The DEB package of 0.4.0 seems to have removed the QT6 dependencies.  Therefore apt now believes those packages can be removed unless explicitly marked.

![image](https://github.com/CDrummond/melodeon/assets/32575346/b651a17d-70f1-4234-975a-10b2fcde8a32)

Minor issue:  There is a typo in the spelling of Lyrion in the .desktop file description

![image](https://github.com/CDrummond/melodeon/assets/32575346/4df25bb3-4595-4928-8d00-1b8f194b8915)

Thank you for the material skin!

**Comment by CDrummond** [comment]
Hopefully fixed in 0.4.1

**Comment by janteau** [comment]
Fixed!
