### ISSUE TITLE
Debian dependancy name changes

### ISSUE THREAD

**Issue by janteau** [CDrummond/melodeon#5]
Not sure if you're building your DEB to be compatible with Debian or Ubuntu, but it seems Debian has renamed the libqt6 packages and removed the t64 suffix.

https://packages.debian.org/bookworm/libqt6gui6
https://packages.debian.org/bookworm/libqt6network6
https://packages.debian.org/bookworm/libqt6widgets6

![image](https://github.com/user-attachments/assets/34b05cf9-1497-4fcc-bdc2-ef0af9247f54)

**Comment by CDrummond** [comment]
Sorry, DEB is Ubuntu only. If you know of a way to make this, or the cmake/cpack script, compatibile please let me know.

**Comment by CDrummond** [comment]
...and so has Ubuntu in 24.10! CMake/CPack files have been updated to reflect this, and therefore so will the next DEB release.
