### ISSUE TITLE
initial window size in 0.4.2 too big

### ISSUE THREAD

**Issue by dfrein** [CDrummond/melodeon#7]
With the new version 0.4.2, the behaviour with regard to window size has changed - now melodeon always starts with nearly full screen geometry on my system. At least with kubuntu 24.10 (plasma 6.1, wayland). In a new config file (melodeon.conf), the entry windowSize=@Size(2496 1376) will always be added, but this does not change when changing size and closing the app, therefore melodeon always starts too big (at least for my taste). Expected behaviour would be that initially and after restarting the app  only use a fraction of the display size would be used (and probably that the last window size would be restored). 
Now I have edited melodeon.conf, which solves the issue for me: windowSize=@Size(800 600)

**Comment by CDrummond** [comment]
Ah! Oops saving of size does not work if not using custom titlebar - fixed for 0.4.3
